layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
     - PTPv3

social_media:
  linkedin: huntk
  twitter: ctfkris
  website: https://ctf.rip

topics:
  - name: Golang
    web_url: https://golang.org/
    image_url: https://i.imgur.com/FfCwhWR.png

  - name: CTF
    web_url: https://ctftime.org
    image_url: https://i.imgur.com/4vLlKgF.png

  - name: Security
    image_url: https://i.imgur.com/89x3N31.png
